version: "3.7"
services:
    line_notify:
        build: .
        container_name: "line_notify_client"
        volumes:
            - .:/home/app
            - /home/app/node_modules
        ports:
            - '8080:8080'
        command:
            "tail -f /dev/null"