nodeapp:
    build: .
    container_name: "nodeapp"
    volumes:
        - ./server:/home/app/nodeapp
        - /home/app/nodeapp/node_modules
        - www:/home/app/nodeapp/out
    restart: always
nginx-proxy:
    image: nginx
    container_name: "nginx"
    ports:
        - '8080:8080'
    volumes:
        - ./nginx:/etc/nginx/conf.d:ro
        - www:/www/app:ro
    links:
        - 'nodeapp'
    restart: always
